{
  "swagger": "2.0",
  "host": "localhost:8000",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "info": {
    "title": "Portal API Documentation",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/deployment": {
      "post": {
        "summary": "create new deployment group",
        "operationId": "postDeployment",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Model 1"
            }
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 2",
              "type": "object"
            },
            "description": "Successful"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/Model 2",
              "type": "object"
            },
            "description": "deployment group created"
          }
        }
      }
    },
    "/deployment/{deploymentId}/manifest": {
      "post": {
        "summary": "create a new manifest revision for a deployment group",
        "operationId": "postDeploymentDeploymentidManifest",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Model 3"
            }
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 3",
              "type": "object"
            },
            "description": "Successful"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/Model 3",
              "type": "object"
            },
            "description": "manifest revision created"
          }
        }
      }
    },
    "/datacenters": {
      "get": {
        "summary": "retrieve a list of available datacenters",
        "operationId": "getDatacenters",
        "tags": [
          "datacenters"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 6",
              "type": "array"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployments": {
      "get": {
        "summary": "retrieve a list of deployment groups",
        "operationId": "getDeployments",
        "tags": [
          "deployments"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 7",
              "type": "array"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}": {
      "get": {
        "summary": "retrieve a deployment group",
        "operationId": "getDeploymentDeploymentid",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 2",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      },
      "put": {
        "summary": "update a deployment group",
        "operationId": "putDeploymentDeploymentid",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Model 13"
            }
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 2",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      },
      "delete": {
        "summary": "delete a deployment group",
        "operationId": "deleteDeploymentDeploymentid",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "default": {
            "schema": {
              "type": "string"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}/activity": {
      "get": {
        "summary": "retrieve the recent activity for a deployment group",
        "operationId": "getDeploymentDeploymentidActivity",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 9",
              "type": "array"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}/state": {
      "get": {
        "summary": "retrieve the current state of the deployment group",
        "operationId": "getDeploymentDeploymentidState",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 10",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      },
      "put": {
        "summary": "perform an action on the deployment group state",
        "operationId": "putDeploymentDeploymentidState",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Model 14"
            }
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 10",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}/services": {
      "get": {
        "summary": "retrieve the services for a deployment group",
        "operationId": "getDeploymentDeploymentidServices",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 12",
              "type": "array"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}/manifest/{revision}": {
      "get": {
        "summary": "retrieve a manifest revision for a deployment group",
        "operationId": "getDeploymentDeploymentidManifestRevision",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          },
          {
            "type": "number",
            "description": "Revision number of manifest",
            "name": "revision",
            "in": "path",
            "required": true
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 3",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      }
    },
    "/deployment/{deploymentId}/service/{name}": {
      "put": {
        "summary": "perform an action on the named service",
        "operationId": "putDeploymentDeploymentidServiceName",
        "parameters": [
          {
            "type": "number",
            "description": "ID of deployment group",
            "name": "deploymentId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Unique name to identify the service",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/Model 15"
            }
          }
        ],
        "tags": [
          "deployment"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Model 11",
              "type": "object"
            },
            "description": "Successful"
          }
        }
      }
    }
  },
  "definitions": {
    "Model 1": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of deployment group"
        },
        "datacenter": {
          "type": "string",
          "description": "datacenter the deployment group belongs to"
        }
      },
      "required": [
        "name",
        "datacenter"
      ]
    },
    "Model 2": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of deployment group"
        },
        "datacenter": {
          "type": "string",
          "description": "datacenter the deployment group belongs to"
        },
        "id": {
          "type": "number",
          "description": "ID of deployment group"
        }
      },
      "required": [
        "name",
        "datacenter",
        "id"
      ]
    },
    "Model 3": {
      "type": "object",
      "properties": {
        "file": {
          "type": "string",
          "description": "JSON file",
          "x-meta": {
            "swaggerType": "file"
          }
        }
      },
      "required": [
        "file"
      ]
    },
    "Model 5": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of datacenter"
        },
        "url": {
          "type": "string",
          "description": "URL of datacenter"
        }
      },
      "required": [
        "name",
        "url"
      ]
    },
    "Model 6": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Model 5",
        "type": "object"
      }
    },
    "Model 7": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Model 2",
        "type": "object"
      }
    },
    "meta": {
      "type": "object"
    },
    "Model 8": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date",
          "description": "Date/time when the activity occurred"
        },
        "type": {
          "type": "string",
          "description": "The type of activity that occurred"
        },
        "meta": {
          "$ref": "#/definitions/meta",
          "type": "object"
        }
      },
      "required": [
        "date",
        "type"
      ]
    },
    "Model 9": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Model 8",
        "type": "object"
      }
    },
    "Model 10": {
      "type": "object",
      "properties": {
        "current": {
          "type": "string",
          "description": "The current state of the deployment group",
          "enum": [
            "started",
            "stopped"
          ]
        }
      },
      "required": [
        "current"
      ]
    },
    "Model 11": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Unique name to identify the service"
        },
        "count": {
          "type": "number",
          "description": "Number of instances of the service",
          "default": 1
        }
      },
      "required": [
        "name"
      ]
    },
    "Model 12": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Model 11",
        "type": "object"
      }
    },
    "Model 13": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of deployment group"
        },
        "datacenter": {
          "type": "string",
          "description": "datacenter the deployment group belongs to"
        }
      }
    },
    "Model 14": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "description": "Action being performed on the deployment group",
          "enum": [
            "start",
            "stop",
            "restart"
          ]
        }
      },
      "required": [
        "action"
      ]
    },
    "Model 15": {
      "type": "object",
      "properties": {
        "count": {
          "type": "number",
          "description": "Number of instances of the service",
          "default": 1
        }
      },
      "required": [
        "count"
      ]
    }
  }
}
